Week2_Complete
JoseGrangerSalgado/software-product-sprint pull request #4
Opened 2021-03-05 01:30 UTC by JoseGrangerSalgado

- Reformatted everything with prettier.
- Added random quote button with
  fetch and java servlet
- Added form submit with fetch
  and java servlet
- Styled everything according to the
   page
- Added Gson to dependencies

2021-03-05 05:54 UTC, josueetcom commented on portfolio/src/main/java/com/google/sps/servlets/RandomServlet.java
> +  private String[] mess = {"He cooks a mean cereal - My Brother", "He is okay, I guess - My Bestfriend", "He can turn on my Netflix, basically a genius - My Mom", "He feeds me - My Dog", "He is the a
"Java code has a column limit of 100 characters." - https://google.github.io/styleguide/javaguide.html#s4.4-column-limit

2021-03-05 06:28 UTC, josueetcom requested changes

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/java/com/google/sps/servlets/RandomServlet.java
> +  private String convertToJsonUsingGson(String[] mess) {
nit: the short form of `message` I've typically seen is `msg`

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/Javascript/main.js
> +var randomMess = document.getElementById("message")
nit: I suggest renaming `randomMess` to `messageElement` or something to help distinguish it from the `randomMessage` below.

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/Javascript/main.js
> +  document.getElementById("myNav2").style.height = "100%";
FYI, using jQuery I think you can replace `document.getElementById("foo")` with `$('#foo')`

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/html/index.html
> +  <div class=Aboutme>
*`"about-me"`

Separate words in ID and class names by a hyphen. - https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/html/index.html
> +  <div id="myNav" class="overlay">
Separate words in ID and class names by a hyphen. - https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/html/index.html
> +  <div id="myNav2" class="overlay">
Separate words in ID and class names by a hyphen. - https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/html/index.html
> +      <button id="playbutton1" onclick="playMusic()"></button>
Separate words in ID and class names by a hyphen. - https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

2021-03-05 06:28 UTC, josueetcom commented on portfolio/src/main/webapp/html/index.html
> +      </div>
Some general note on IDs.

1. You usually want IDs for completely unique elements that either need to be referenced uniquely via JavaScript or styled uniquely via CSS or serve as an anchor point for the page. Otherwise the general pattern is to use the same class name for elements that should be styled similarly. If no styling is necessary then a class is not needed either.
2. I don't think I've seen HTML IDs that aren't quoted before. I don't see any issue with it in the style guide though.
3. The general casing pattern I've seen for IDs is `lower-hyphen-case`

2021-03-05 15:03 UTC, JoseGrangerSalgado commented on portfolio/src/main/java/com/google/sps/servlets/RandomServlet.java
> +  private String[] mess = {"He cooks a mean cereal - My Brother", "He is okay, I guess - My Bestfriend", "He can turn on my Netflix, basically a genius - My Mom", "He feeds me - My Dog", "He is the a
Fixed

2021-03-05 15:04 UTC, JoseGrangerSalgado commented on portfolio/src/main/java/com/google/sps/servlets/RandomServlet.java
> +  private String convertToJsonUsingGson(String[] mess) {
Fixed

2021-03-05 15:06 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/Javascript/main.js
> +var randomMess = document.getElementById("message")
Fixed

2021-03-05 15:07 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/Javascript/main.js
> +  document.getElementById("myNav2").style.height = "100%";
Going to research this, thanks.

2021-03-05 16:17 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/html/index.html
> +  <div class=Aboutme>
Fixed

2021-03-05 16:17 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/html/index.html
> +  <div id="myNav" class="overlay">
Fixed

2021-03-05 16:17 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/html/index.html
> +  <div id="myNav2" class="overlay">
Fixed

2021-03-05 16:17 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/html/index.html
> +      <button id="playbutton1" onclick="playMusic()"></button>
Fixed

2021-03-05 16:17 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/html/index.html
> +      </div>
Fixed

2021-03-06 04:04 UTC, josueetcom approved these changes
Approving to get you unblocked so you can merge this. The formatting issues can be fixed separately. I haven't quite figured out why the prettier pre-commit hook doesn't work yet :/

2021-03-06 04:04 UTC, josueetcom commented on portfolio/src/main/java/com/google/sps/servlets/RandomServlet.java
> +  "He feeds me - My Dog", "He is the apex human - Elon Musk(probably)"};
Interesting formatting 🤔 

For future reference, I think prettier can format this file via `npx prettier --write`

2021-03-06 04:04 UTC, josueetcom commented on portfolio/src/main/webapp/Javascript/main.js
> +    showSlides(slideIndex += n);
Looks like the indentation here (and in the rest of the file) is off. It's probably due to Cloud Shell Editor defaulting to 4 space indents. Feel free to address separately.

2021-03-06 07:25 UTC, merged