Week3_Complete
JoseGrangerSalgado/software-product-sprint pull request #5
Opened 2021-03-11 03:16 UTC by JoseGrangerSalgado

-Completed Week3 using Datastore
-Added alt to images
-Fixed Resume link
-Made the animation and background of the intro much better

2021-03-11 03:32 UTC, JoseGrangerSalgado commented
Sorry I was just exploring how github worked on the website, sorry for the opening and closing

2021-03-11 08:47 UTC, josueetcom requested changes
Lots of formatting issues. I wasn't able to point them all out but I think you can fix most of them (except for CSS property alphabetization) using Prettier (check our team chat)

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/java/com/google/sps/data/Task.java
> +
nit: remove extra blank line

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/java/com/google/sps/servlets/RandomServlet.java
>    "He feeds me - My Dog", "He is the apex human - Elon Musk(probably)"};
Tip: you could consider having one quote per line

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +    width:92.5925925925926vh;
Interesting values 🤔

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +    background: url(../Images/water.gif) no-repeat center center fixed;
FYI, GitHub tells me that `water.gif` is blank. Not sure why

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +    overflow:hidden;
"Alphabetize declarations." - https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order

Sorry, I forgot to mention this the first few weeks. In general it's helpful so that:
1. You can quickly find a property
2. You can more easily detect/prevent duplicates (e.g. you have two `padding` values here, I believe the second one overrides the first)

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +    text-align: center;
"Alphabetize declarations." - https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +    color:#fcfcfc;
"Alphabetize declarations." - https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +header a, a:visited {
"Separate rules by new lines." - https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation

"Separate selectors and declarations by new lines." - https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +header h2{
"Separate rules by new lines." - https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
>  .slideshow-container {
"Separate rules by new lines." - https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +  }
```suggestion
}
```

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +}
"Separate rules by new lines." - https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation

2021-03-11 08:47 UTC, josueetcom commented on portfolio/src/main/webapp/css/mainstyles.css
> +    pointer-events:none;
Indent by 2 spaces at a time.

https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation

2021-03-11 15:28 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/css/mainstyles.css
> +    width:92.5925925925926vh;
I had to convert these values from px in order to keep it consistent to all screens, but I could probably round them up

2021-03-11 15:29 UTC, JoseGrangerSalgado commented on portfolio/src/main/webapp/css/mainstyles.css
> +    background: url(../Images/water.gif) no-repeat center center fixed;
Yeah I don't know why either, it is definetly working for me

2021-03-11 22:04 UTC, josueetcom approved these changes

2021-03-11 22:04 UTC, josueetcom commented on portfolio/src/main/webapp/Javascript/main.js
> +    fetch('/list-tasks').then(response => response.json()).then((tasks) => {
JS indentation is supposed to be 2 spaces as well. Though I think this is a result of my prettier setup instructions not taking JS files into considerations :P.

I think you can fix it using the command `npx prettier --write portfolio`.

2021-03-12 00:13 UTC, merged

2021-03-12 07:40 UTC, josueetcom commented on portfolio/src/main/webapp/Javascript/main.js
> +var audio = document.getElementById("audio");
I forgot to mention earlier (it's hard to remember everything) but the style guide also says "Declare all local variables with either `const` or `let`"

https://google.github.io/styleguide/jsguide.html#features-use-const-and-let